module.exports = {
    ERR_INTERNAL : 1,
    ERR_EMPTY_EMAIL : 20,
    ERR_INVAIL_EMAIL : 21,
    ERR_EXISTS_EMAIL : 22,
    ERR_EMPTY_PASSWORD : 30,
    ERR_INVAIL_PASSWORD : 31,
    ERR_WRONG_PASSWORD : 32,
    ERR_USER_NOT_EXISTS : 40,
    ERR_INVAILD_REFRESH_TOKEN : 41,
};